#!/usr/bin/env python3
"""Build per-harness subagent files from the shared sources in agents/.

Each agents/<name>.md has TOML frontmatter between `+++` lines:

    +++
    name = "..."
    description = "..."
    [claude]            # merged into the Claude Code YAML frontmatter
    [opencode]          # merged into the OpenCode YAML frontmatter (mode: subagent is added)
    [codex]             # merged into the Codex agent TOML
    +++
    <prompt body, shared by all three>

Outputs (committed):
    dist/claude/agents/<name>.md
    dist/opencode/agents/<name>.md
    dist/codex/agents/<name>.toml

Usage:
    python3 scripts/build-agents.py           # write dist/
    python3 scripts/build-agents.py --check   # exit 1 if dist/ is stale
"""

import json
import re
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "agents"
DIST = ROOT / "dist"
HEADER = "generated by scripts/build-agents.py from agents/{name}.md, do not edit"
BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"\+\+\+\n(.*?)\n\+\+\+\n(.*)\Z", text, re.S)
    if not m:
        sys.exit(f"{path}: missing +++ TOML frontmatter")
    meta = tomllib.loads(m.group(1))
    for key in ("name", "description"):
        if not isinstance(meta.get(key), str) or not meta[key]:
            sys.exit(f"{path}: frontmatter needs a non-empty `{key}`")
    if meta["name"] != path.stem:
        sys.exit(f"{path}: name {meta['name']!r} must match the file name")
    return meta, m.group(2).strip() + "\n"


# --- YAML (only the subset we emit: maps, strings, numbers, bools) ---------

def yaml_scalar(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        if BARE_KEY.match(v) and v not in ("true", "false", "null", "yes", "no"):
            return v
        return json.dumps(v, ensure_ascii=False)
    sys.exit(f"unsupported YAML value: {v!r}")


def yaml_lines(d, indent=0):
    out = []
    for k, v in d.items():
        key = k if BARE_KEY.match(k) else json.dumps(k)
        if isinstance(v, dict):
            out.append(" " * indent + f"{key}:")
            out += yaml_lines(v, indent + 2)
        else:
            out.append(" " * indent + f"{key}: {yaml_scalar(v)}")
    return out


def markdown_agent(front, body, name):
    lines = ["---", *yaml_lines(front), "---", "", f"<!-- {HEADER.format(name=name)} -->", "", body]
    return "\n".join(lines)


# --- TOML (flat keys + tables) ---------------------------------------------

def toml_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)
    if isinstance(v, list):
        return "[" + ", ".join(toml_value(x) for x in v) + "]"
    sys.exit(f"unsupported TOML value: {v!r}")


def toml_multiline(s):
    # Basic multi-line string: escape backslashes and any run of three quotes.
    s = s.replace("\\", "\\\\").replace('"""', '""\\"')
    return '"""\n' + s + '"""'


def toml_table(d, prefix=""):
    flat = [(k, v) for k, v in d.items() if not isinstance(v, dict)]
    tables = [(k, v) for k, v in d.items() if isinstance(v, dict)]
    out = [f"{k} = {toml_value(v)}" for k, v in flat]
    for k, v in tables:
        name = f"{prefix}{k}"
        out += ["", f"[{name}]", *toml_table(v, name + ".")]
    return out


def codex_agent(meta, body):
    cfg = dict(meta.get("codex", {}))
    top = {"name": meta["name"], "description": meta["description"]}
    flat = {k: v for k, v in cfg.items() if not isinstance(v, dict)}
    tables = {k: v for k, v in cfg.items() if isinstance(v, dict)}
    lines = [f"# {HEADER.format(name=meta['name'])}"]
    lines += toml_table({**top, **flat})
    lines.append(f"developer_instructions = {toml_multiline(body)}")
    if tables:
        lines += toml_table(tables)
    text = "\n".join(lines) + "\n"
    tomllib.loads(text)  # fail loudly if we ever emit invalid TOML
    return text


def build(out_root):
    sources = sorted(SRC.glob("*.md"))
    if not sources:
        sys.exit(f"no agent sources in {SRC}")
    for tool in ("claude", "opencode", "codex"):
        (out_root / tool / "agents").mkdir(parents=True, exist_ok=True)
    written = []
    for path in sources:
        meta, body = parse(path)
        name = meta["name"]

        claude = {"name": name, "description": meta["description"], **meta.get("claude", {})}
        opencode = {"description": meta["description"], "mode": "subagent", **meta.get("opencode", {})}
        files = {
            out_root / "claude" / "agents" / f"{name}.md": markdown_agent(claude, body, name),
            out_root / "opencode" / "agents" / f"{name}.md": markdown_agent(opencode, body, name),
            out_root / "codex" / "agents" / f"{name}.toml": codex_agent(meta, body),
        }
        for dest, content in files.items():
            dest.write_text(content, encoding="utf-8")
            written.append(dest.relative_to(out_root))
    return written


def tree(root):
    return {p.relative_to(root): p.read_bytes() for p in root.rglob("*") if p.is_file()}


def main():
    if "--check" in sys.argv[1:]:
        with tempfile.TemporaryDirectory() as tmp:
            build(Path(tmp))
            fresh, current = tree(Path(tmp)), tree(DIST) if DIST.exists() else {}
        stale = sorted(str(p) for p in fresh.keys() | current.keys() if fresh.get(p) != current.get(p))
        if stale:
            print("dist/ is stale, run: python3 scripts/build-agents.py", *stale, sep="\n  ")
            sys.exit(1)
        print("dist/ is up to date")
        return
    # Rebuild from scratch so agents removed from agents/ disappear from dist/.
    for tool in ("claude", "opencode", "codex"):
        for old in (DIST / tool / "agents").glob("*"):
            old.unlink()
    for rel in build(DIST):
        print(f"wrote dist/{rel}")


if __name__ == "__main__":
    main()
